store_django/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('basket/', views.UserBasket.as_view(), name='basket'),
    path('basket/buy/', views.BuyBasket.as_view(), name='buy'),
    path('refunds/', views.RefundsUser.as_view(), name='refunds_user'),
    path('refunds/refund/<int:refund_id>', views.Refund.as_view(), name='refund'),
    path('create_application/', views.CreateApplicationOnRefund.as_view(), name='create_application'),
    path('applications/', views.AplicationsOnRefundView.as_view(), name='applications'),
    path('applications_for_moder/', views.ApplicationsOnRefundForModer.as_view(), name='applications_for_moder'),
    path('refund_accept/', views.RefundAccept.as_view(), name='refund_accept'),
    path('basket/addication_balance/', views.AddicationBalance.as_view(), name='addication_balance')
]

store_django/store_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('order/', include('order.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store_django/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterUsers, name='register'),
    path('register/login/', views.LoginUser.as_view(), name='login'),
    path('profile/', views.Profile.as_view(), name='profile')
]

store_django/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Status(models.Model):
    status_name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.status_name


class Users(AbstractUser):
    user_status = models.ForeignKey(
        to=Status,
        on_delete=models.CASCADE,
        default=1
    )
    money_balance = models.IntegerField(default=0)
    
    def __str__(self):
        return self.username

store_django/users/forms.py
from django import forms
from .models import Users
from products.models import Products
from django.contrib.auth.forms import UserCreationForm


class RegisterUser(UserCreationForm):
    class Meta:
        model = Users
        fields = [
            'username',
            'email',
            'password1',
            'password2'
        ]
        
        
class UpdateProductForm(forms.ModelForm):
    class Meta:
        model = Products
        fields = [
            'product_name',
            'product_description',
            'price',
            'quantity',
            'product_cat',
            'product_img',
            'public'
        ]

store_django/users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.views import LoginView
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse_lazy
from .forms import RegisterUser
from .models import Users
from products.models import Products
from order.models import Basket
            
            
def RegisterUsers(request):
    if request.method == 'POST':
        form = RegisterUser(request.POST)
        if form.is_valid():
            user = form.save()
            user.set_password(request.POST['password1'])
            user.save()
            user = Users.objects.get(username=request.POST['username'])
            Basket.objects.create(
                owner_basket_id=user.pk
            )
            status = 'Вы успешно зарегистрированы, теперь необходимо войти в аккаунт'
        else:
            status = 'что то пошло не так :('

    else:
        form = RegisterUser()
        status = ''
    
    return render(request, 'users/register.html', {'form': form, 'status': status})
    
    
class LoginUser(LoginView):
    form_class = AuthenticationForm
    template_name = 'users/login.html'
    
    def get_success_url(self):
        return reverse_lazy('home')
    
    
class Profile(View):
    def get(self, request):
        try:
            user_pk = self.request.user.pk
            user = Users.objects.get(pk=user_pk)
            user_products = Products.objects.filter(owner_user=user_pk)
            context = {
                'user': user,
                'user_products': user_products,
                'status': ''
            }
        except:
            context = {
                'user': '',
                'user_products': '',
                'status': 'необходимо зарегистрироватся на сайте'
            }
        
        return render(request, 'users/profile.html', context)
    
    def post(self, request):
        user_pk = self.request.user.pk
        user = Users.objects.get(pk=user_pk)
        user_products = Products.objects.filter(owner_user=user_pk)
        button = request.POST['button']
        if button == 'add_product':
            user_status = str(user.user_status)
            if user_status == 'seller' or user_status == 'moder':
                return redirect('add_product')
            else:
                pass
        else:
            Products.objects.get(pk=button).delete()
        
        return render(request, 'users/profile.html', {'user': user, 'user_products': user_products})

store_django/users/templates/users/login.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Отправить</button>
    </form>
</body>
</html>

store_django/users/templates/users/profile.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Profile</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <div>
        <h2>Информация о пользователе:</h2>
        <p>Ник: {{user.username}}</p>
        <p>Электронная почта: {{user.email}}</p>
        <p>статус пользователя: {{user.user_status}}</p>
        <button type="button">
            <a href="{% url 'order:basket' %}">Корзина пользователя</a>
        </button>
        {% if user.user_status.status_name == 'moder' %}
        <button type="button">
            <a href="{% url 'order:applications_for_moder' %}">Заявки на возврат</a>
        </button>
        {% else %}
        <p>gvsdchgsdchgv</p>
        {{status}}
        {% endif %}
    </div>
    <br>
    <div>
        <h2>Продукты пользователя:</h2>
        <button type="button">
            <a href="{% url 'add_product' %}">Выставить продукт</a>
        </button>
        <form method="post">
            {% csrf_token %}
            <button name="button" value="add_product" type="submit">Добавить продукты</button>
        </form>
        {% for i in user_products %}
        <br>
        <div>
            <p>id продукта: {{i.pk}}</p>
            <img src="{{i.product_img.url}}" alt="где фото?">
            <p>Назавание: {{i.product_name}}</p>
            <p>Описание: {{i.product_description}}</p>
            <p>Цена: {{i.price}}</p>
            <p>Количество: {{i.quantity}}</p>
            <p>Категория: {{i.product_cat}}</p>
            {% if i.public == True %}
            <p>Публичный</p>
            {% else %}
            <p>Не публичный</p>
            {% endif %}
            <p>Время выставления на продажу: {{i.product_create_time}}</p>
            <form method="post">
                {% csrf_token %}
                <button name="button" value="{{i.pk}}" type="submit">Удалить продукт</button>
                <button type="button">
                    <a href="{{ i.get_absolute_url }}">Обновить продукт</a>
                </button>
            </form>
        </div>
        {% endfor %}
    </div>
</body>
</html>

store_django/users/templates/users/register.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Регистрация</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Зарегистрироватся</button>
    </form>
    {{status}}
    <br>
    <button type="button">
        <a href="{% url 'users:login' %}">Вход в аккаунт</a>
    </button>
</body>
</html>