store_django/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('basket/', views.UserBasket.as_view(), name='basket'),
    path('basket/buy/', views.BuyBasket.as_view(), name='buy'),
    path('refunds/', views.RefundsUser.as_view(), name='refunds_user'),
    path('refunds/refund/<int:refund_id>', views.Refund.as_view(), name='refund'),
    path('create_application/', views.CreateApplicationOnRefund.as_view(), name='create_application'),
    path('applications/', views.AplicationsOnRefundView.as_view(), name='applications'),
    path('applications_for_moder/', views.ApplicationsOnRefundForModer.as_view(), name='applications_for_moder'),
    path('refund_accept/', views.RefundAccept.as_view(), name='refund_accept'),
    path('basket/addication_balance/', views.AddicationBalance.as_view(), name='addication_balance')
]

store_django/store_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('order/', include('order.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store_django/order/models.py
from django.db import models
from users.models import Users
from products.models import Products
from django.urls import reverse


class Basket(models.Model):
    owner_basket = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    basket_sum = models.IntegerField(
        default=0
    )
    product_quantity = models.IntegerField(
        default=0
    )
    
    
class Product_in_basket(models.Model):
    where_product = models.ForeignKey(
        to=Basket,
        on_delete=models.CASCADE
    )
    product = models.ForeignKey(
        to=Products,
        on_delete=models.CASCADE
    )
    
    def __str__(self):
        return str(self.where_product)
    
    
class Refunds(models.Model):
    whose_refund = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    refund = models.CharField(max_length=200)
    date_create = models.DateTimeField(auto_now_add=True)
    
    def get_absolute_url(self):
        return reverse('order:refund', kwargs={'refund_id': self.pk})
    
    def __str__(self):
        return self.whose_refund.username
    
    
class ApplicationOnRefund(models.Model):
    whose_application = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    content = models.TextField()
    accept = models.BooleanField(
        null=True,
        blank=True,
        default=''
    )
    date_create = models.DateTimeField(auto_now_add=True)
    
    def get_absolute_url(self):
        return reverse('order:application', kwargs={'application_id': self.pk})
    
    def __str__(self):
        return self.whose_application.username

store_django/order/forms.py
from django import forms
from .models import ApplicationOnRefund


class BuyBasket(forms.Form):
    kard_number = forms.CharField(
        max_length=16,
        label='Номер карточки:'
    )
    pincode = forms.CharField(
        max_length=4,
        label='Пинкод:'
    )
    telephone_number = forms.CharField(
        max_length=16,
        label='Номер телефона:'
    )
    
    
class ApplicationOnRefundForm(forms.ModelForm):
    class Meta:
        model = ApplicationOnRefund
        fields = ['content', ]
        
        
class RefundAcceptForm(forms.Form):
    money = forms.CharField(
        max_length=20,
        label='деньги потраченые пользователем'
    )
    id = forms.IntegerField(label='id продукта')
    quantity = forms.IntegerField(label='Количество возвращаемого товара одного типа')
    
    
class AddicationBalanceForm(forms.Form):
    money = forms.IntegerField(label='Количество денег которое вы хотите положить себе на баланс')

store_django/order/views.py
from django.shortcuts import render, redirect
from django.views.generic import FormView, CreateView
from django.views import View
from .models import Basket, Product_in_basket, Refunds, ApplicationOnRefund
from products.models import Products
from .forms import BuyBasket, ApplicationOnRefundForm, RefundAcceptForm, AddicationBalanceForm
from django.urls import reverse_lazy
from users.models import Users


class AddicationBalance(FormView):
    template_name = 'order/addication_balance.html'
    form_class = AddicationBalanceForm
    success_url = reverse_lazy('order:basket')
    
    def form_valid(self, form):
        user = Users.objects.get(pk=self.request.user.pk)
        user.money_balance += int(self.request.POST['money'])
        user.save()
        
        return super().form_valid(form)


class UserBasket(View):
    def get(self, request):
        user_pk = self.request.user.pk
        user = Users.objects.get(pk=user_pk)
        basket = Basket.objects.get(owner_basket=user_pk)
        products_in_basket = Product_in_basket.objects.filter(where_product=basket.pk)
        
        return render(request, 'order/basket.html', {'basket': basket, 'products_in_basket': products_in_basket, 'user': user})
    
    def post(self, request):
        user_pk = self.request.user.pk
        basket = Basket.objects.get(owner_basket=user_pk)
        products_in_basket = Product_in_basket.objects.filter(where_product=basket.pk)
        button = request.POST['button']
        basket = Basket.objects.get(owner_basket=user_pk)
        product_in_basket = Product_in_basket.objects.get(pk=button)
        basket.basket_sum -= product_in_basket.product.price
        basket.product_quantity -= 1
        product = Products.objects.get(pk=product_in_basket.product.pk)
        product.quantity += 1
        product.save()
        basket.save()
        product_in_basket.delete()
        
        return render(request, 'order/basket.html', {'basket': basket, 'products_in_basket': products_in_basket})
    
    
class BuyBasket(FormView):
    form_class = BuyBasket
    template_name = 'order/buy_basket.html'
    success_url = reverse_lazy('home')
    
    def post(self, request, *args, **kwargs):
        user_pk = self.request.user.pk
        user_basket = Basket.objects.get(owner_basket=user_pk)
        if user_basket.product_quantity == 0 and user_basket.basket_sum == 0:
            pass
        else:
            #логика отправки данных и покупки
            products = Product_in_basket.objects.filter(where_product=user_basket.pk)
            all_product = []
            for i in products:
                all_product.append(i.product.pk)
                all_product.append(i.product.product_name)
                all_product.append(i.product.price,)
            Refunds.objects.create(
                whose_refund_id=self.request.user.pk,
                refund=all_product
            )
            user = Users.objects.get(pk=user_pk)
            print(user.money_balance, user_basket.basket_sum)
            new_balance = user.money_balance - user_basket.basket_sum
            print(new_balance)
            if new_balance <= 0:
                pass
            else:
                user.money_balance = new_balance
                user.save()
                products.delete()
                user_basket.basket_sum = 0
                user_basket.product_quantity = 0
                user_basket.save()
            
        return super().post(request, *args, **kwargs)
    
    
class RefundsUser(View):
    def get(self, request):
        pk_application = request.session['pk_application']
        user_pk = ApplicationOnRefund.objects.get(pk=pk_application).whose_application.pk
        refunds = Refunds.objects.filter(whose_refund=user_pk)
        
        return render(request, 'order/refunds_list.html', {'refunds': refunds})

    def post(self, request):
        pk_application = request.session['pk_application']
        user_pk = ApplicationOnRefund.objects.get(pk=pk_application).whose_application.pk
        refunds = Refunds.objects.filter(whose_refund=user_pk)
        
        return render(request, 'order/refunds_list.html', {'refunds': refunds})
    
    
class Refund(View):
    def get(self, request, **kwargs):
        refund = Refunds.objects.get(pk=kwargs['refund_id'])
        
        return render(request, 'order/refund.html', {'refund': refund})

    def post(self, request, **kwargs):
        button = request.POST['button']
        pk_application = request.session['pk_application']
        application = ApplicationOnRefund.objects.get(pk=pk_application)
        if button == 'accept':
            request.session['refund_user_pk'] = application.whose_application.pk
            return redirect('order:refund_accept')
        else:
            application.accept = False
            application.save()
        
        return redirect('order:applications')
    
    
class RefundAccept(FormView):
    template_name = 'order/refund_accept.html'
    form_class = RefundAcceptForm
    success_url = reverse_lazy('order:applications_for_moder')
    
    def form_valid(self, form):
        user_pk = self.request.session['refund_user_pk']
        money = self.request.POST['money']
        user = Users.objects.get(pk=user_pk)
        user.money_balance += int(money)
        user.save()
        pk_application = self.request.session['pk_application']
        application = ApplicationOnRefund.objects.get(pk=pk_application)
        application.accept = True
        application.save()
        pk_product = self.request.POST['id']
        product = Products.objects.get(pk=pk_product)
        product.quantity += int(self.request.POST['quantity'])
        product.save()
        
        return super().form_valid(form)
    
    
class CreateApplicationOnRefund(CreateView):
    form_class = ApplicationOnRefundForm
    template_name = 'order/create_application.html'
    success_url = reverse_lazy('order:applications')

    def form_valid(self, form):
        valid_f = form.save(commit=False)
        valid_f.whose_application_id = self.request.user.pk
        return super().form_valid(form)
    
    
class ApplicationsOnRefundForModer(View):
    def get(self, request):
        applications = ApplicationOnRefund.objects.filter(whose_application=self.request.user.pk, accept='')
        
        return render(request, 'order/applications_for_moder.html', {'applications': applications})

    def post(self, request):
        request.session['pk_application'] = request.POST['pk_application']
        
        return redirect('order:refunds_user')
           
    
class AplicationsOnRefundView(View):
    def get(self, request):
        applications = ApplicationOnRefund.objects.filter(whose_application=self.request.user.pk)
        
        return render(request, 'order/applications.html', {'applications': applications})
    
    def post(self, request):
        applications = ApplicationOnRefund.objects.filter(whose_application=self.request.user.pk)
        button = request.POST['button']
        ApplicationOnRefund.objects.get(pk=button).delete()
        
        return render(request, 'order/applications.html', {'applications': applications})

store_django/order/templates/order/addication_balance.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Addication balance</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Пополнить</button>
    </form>
</body>
</html>

store_django/order/templates/order/applications.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Applications</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <div>
        <button type="button">
            <a href="{% url 'order:create_application' %}">Создать заявку</a>
        </button>
    </div>
    {% for i in applications %}
    <br>
    <div>
        <p>{{i.content}}</p>
        <p>{{i.date_create}}</p>
        {% if i.accept == True %}
        <p>Заявка одобрена</p>
        {% elif i.accept == False %}
        <p>Заявка отклонена</p>
        {% else %}
        <p>Не прочитана</p>
        {% endif %}
        <form method="post">
            {% csrf_token %}
            <button name="button" value="{{i.pk}}" type="submit">Удалить</button>
        </form>
    </div>
    {% endfor %}
</body>
</html>

store_django/order/templates/order/applications_for_moder.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Application for moder</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    {% for i in applications %}
    <br>
    <div>
        <p>{{i.date_create}}</p>
        <p>{{i.content}}</p>
        <form method="post">
            {% csrf_token %}
            <button name="pk_application" value="{{i.pk}}" type="submit">перейти к покупкам пользователя</button>
        </form>
    </div>
    {% endfor %}
</body>
</html>

store_django/order/templates/order/basket.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>basket</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <div>
        <button type="button">
            <a href="{% url 'order:addication_balance' %}">Пополнение баланса</a>
        </button>
        <p>{{user.money_balance}}</p>
    </div>
    <br>
    <div>
        <h2>Корзина</h2>
        {% for i in products_in_basket %}
        <br>
        <div>
            <p>id: {{i.pk}}</p>
            <p>Название: {{i.product.product_name}}</p>
            <p>Цена: {{i.product.price}}</p>
            <p>Количество: {{i.product.quantity}}</p>
            <form method="post">
                {% csrf_token %}
                <button name="button" value="{{i.pk}}" type="submit">Убрать</button>
            </form>
        </div>
        {% endfor %}
    </div>
<br>
<div>
    <p>Общая сумма корзины: {{basket.basket_sum}}</p>
    <p>Общее количество товаров: {{basket.product_quantity}}</p>
    <form method="post">
        {% csrf_token %}
        <button type="button">
            <a href="{% url 'order:buy' %}">Оплатить</a>
        </button>
    </form>
</div>
</body>
</html>

store_django/order/templates/order/buy_basket.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Buy page</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <button type="submit">Подтвердить</button>
    </form>
</body>
</html>

store_django/order/templates/order/create_application.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create application</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <div>
        <h3>Правила написания заявления</h3>
        <h3>Если ваше заявление не будет соответствовать правилам написания то модератор имеет полное право отклонить ваше заявление</h3>
        <p>Ваше заявление должно содержать дату покупки, какой продукт вы хотите вернуть(название) и почему вы хотите вернуть товар</p>
    </div>
    <br>
    <div>
        <form method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Отправить</button>
        </form>
    </div>
</body>
</html>

store_django/order/templates/order/refund.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Refund</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <p>{{refund.refund}}</p>
    <p>{{refund.date_create}}</p>
    <form method="post">
        {% csrf_token %}
        <button name="button" value="accept" type="submit">Одобрить</button>
        <button name="button" value="not_accept" type="submit">Отклонить</button>
    </form>
</body>
</html>

store_django/order/templates/order/refund_accept.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Refund accept</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Отправить</button>
    </form>
</body>
</html>

store_django/order/templates/order/refunds_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Refunds list</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    {% for i in refunds %}
    <br>
    <div>
        <p>Возврат: {{i.date_create}}</p>
        <button type="button">
            <a href="{{ i.get_absolute_url }}">Подробнее</a>
        </button>
    </div>
    {% endfor %}
</body>
</html>