store_django/order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('basket/', views.UserBasket.as_view(), name='basket'),
    path('basket/buy/', views.BuyBasket.as_view(), name='buy'),
    path('refunds/', views.RefundsUser.as_view(), name='refunds_user'),
    path('refunds/refund/<int:refund_id>', views.Refund.as_view(), name='refund'),
    path('create_application/', views.CreateApplicationOnRefund.as_view(), name='create_application'),
    path('applications/', views.AplicationsOnRefundView.as_view(), name='applications'),
    path('applications_for_moder/', views.ApplicationsOnRefundForModer.as_view(), name='applications_for_moder'),
    path('refund_accept/', views.RefundAccept.as_view(), name='refund_accept'),
    path('basket/addication_balance/', views.AddicationBalance.as_view(), name='addication_balance')
]

store_django/products/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Main.as_view(), name='home'),
    path('product/', views.Product.as_view()),
    path('product/reviews/', views.ReviewsPage.as_view(), name='reviews'),
    path('product/reviews/add_review/', views.AddReview.as_view()),
    path('add_product/', views.AddProduct.as_view(), name='add_product'),
<<<<<<< HEAD
    path('update/<int:pk>/', views.UpdateProduct.as_view(), name='update')
=======
    path('categorys/', views.categorys),
    path('users/profile/update/<int:pk>/', views.UpdateProduct.as_view())
>>>>>>> 29fdf43b36165b945ad51d0b485ad2370d31a970
]

store_django/store_django/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls')),
    path('users/', include('users.urls', namespace='users')),
    path('order/', include('order.urls', namespace='order'))
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store_django/users/urls.py
from django.urls import path
from . import views

app_name = "users"

urlpatterns = [
    path('register/', views.RegisterUsers, name='register'),
    path('register/login/', views.LoginUser.as_view(), name='login'),
    path('profile/', views.Profile.as_view(), name='profile')
]

store_django/products/models.py
from django.db import models
from users.models import Users
from django.urls import reverse


class Category(models.Model):
    cat_name = models.CharField(max_length=20)
    
    def __str__(self):
        return self.cat_name
    
    
class Products(models.Model):
    owner_user = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    product_img = models.ImageField(upload_to='product_imgs')
    product_name = models.CharField(max_length=30)
    product_description = models.TextField()
    price = models.IntegerField()
    quantity = models.IntegerField()
    product_cat = models.ForeignKey(
        to=Category,
        on_delete=models.CASCADE,
        db_index=True
    )
    public = models.BooleanField(
        default=True,
        db_index=True
    )
    product_create_time = models.DateTimeField(auto_now_add=True)
    
    def get_absolute_url(self):
        return reverse('update', kwargs={'pk': self.pk})

    def __str__(self):
        return self.product_name
    
    class Meta:
        ordering = ['-product_create_time']
        indexes = [
            models.Index(fields=['-product_create_time'])
        ]
    
    
class Reviews(models.Model):
    where_review = models.ForeignKey(
        to=Products,
        on_delete=models.CASCADE
    )
    owner_review = models.ForeignKey(
        to=Users,
        on_delete=models.CASCADE
    )
    review_name = models.CharField(max_length=15)
    review_content = models.CharField(max_length=50)
    review_create_time = models.DateTimeField(auto_now_add=True)

store_django/products/forms.py
from django import forms
from .models import Reviews, Products


class AddReview(forms.ModelForm):
    class Meta:
        model = Reviews
        fields = [
            'review_name',
            'review_content'
        ]
        
        
class AddProduct(forms.ModelForm):
    class Meta:
        model = Products
        fields = [
            'product_img',
            'product_name',
            'product_description',
            'price',
            'quantity',
            'product_cat'
        ]

store_django/products/views.py
from django.shortcuts import render, redirect
<<<<<<< HEAD
from django.views.generic import FormView, CreateView, UpdateView
from .models import Products, Reviews
=======
from django.views.generic import ListView, FormView, DetailView, CreateView, UpdateView
from .models import Products, Reviews, Category
>>>>>>> 29fdf43b36165b945ad51d0b485ad2370d31a970
from order.models import Basket, Product_in_basket
from users.models import Users
from django.views import View
from .forms import AddReview, AddProduct
from django.urls import reverse, reverse_lazy


class Main(View):
    def get(self, request):
        products = Products.objects.filter(public=True)
        
        return render(request, 'products/main.html', {'products': products})
    
    def post(self, request):
        products = Products.objects.filter(public=True)
        button = request.POST['button']
        
        if button == 'filter':
            product_category = request.POST['product_cat']
            if product_category == 'all':
                pass
            else:
                products = Products.objects.filter(product_cat=product_category, public=True)
        else:
            request.session['product_pk'] = button
            return redirect('product/')
        
        return render(request, 'products/main.html', {'products': products})
    
    
class Product(View):
    def get(self, request):
        product_pk = request.session['product_pk']
        product = Products.objects.get(pk=product_pk)
        status = ''
        
        return render(request, 'products/product.html', {'product': product, 'status': status})
    
    def post(self, request):
        product_pk = request.session['product_pk']
        product = Products.objects.get(pk=product_pk)
        button = request.POST['button']
        
        if button == 'hide':
            try:
                user_pk = self.request.user.pk
                user_uniform = Users.objects.get(pk=user_pk)
                user_status = str(user_uniform.user_status)
                if user_status == 'moder':
                    product.public = False
                    product.save()
                    status = 'продукт успешно скрыт'
                else:
                    status = 'функция только для модераторов'
            except:
                status = 'необходимо зарегистрироватся на сайте'
        else:
            if product.quantity > 0:
                try:
                    user = self.request.user
                    user_basket = Basket.objects.get(owner_basket=user)
                    Product_in_basket.objects.create(
                        where_product_id=user_basket.pk,
                        product_id=product_pk
                    )
                
                    product.quantity -= 1
                    product.save()
                    user_basket.basket_sum += product.price
                    user_basket.product_quantity += 1
                    user_basket.save()
                    status = 'Продукт успешно добавлен в корзину!'
                except:
                    status = 'необходимо зарегистрироватся на сайте'
            else:
                status = 'Данный продукт уже закончился :('
                    
        
        return render(request, 'products/product.html', {'product': product, 'status': status})
    
    
class UpdateProduct(UpdateView):
    model = Products
    fields = [
        'product_img',
        'product_name',
        'product_description',
        'price',
        'quantity',
        'product_cat'
    ]
    template_name = 'products/update_product.html'
    success_url = reverse_lazy('users:profile')
    
    
class ReviewsPage(View):
    def get(self, request):
        product_pk = request.session['product_pk']
        reviews = Reviews.objects.filter(where_review=product_pk)
        
        return render(request, 'products/reviews.html', {'reviews': reviews})
    
    def post(self, request):
        product_pk = request.session['product_pk']
        reviews = Reviews.objects.filter(where_review=product_pk)
        user = self.request.user
        review_pk = request.POST['button']
        review = Reviews.objects.get(pk=review_pk)
        if review.owner_review_id == user.pk:
            review.delete()
        else:
            pass
        
        return render(request, 'products/reviews.html', {'reviews': reviews})
    
    
class AddReview(FormView):
    form_class = AddReview
    template_name = 'products/add_review.html'
    success_url = reverse_lazy('reviews')
    
    def post(self, request, *args, **kwargs):
        try:
            product_pk = request.session['product_pk']
            Reviews.objects.create(
                where_review_id=product_pk,
                owner_review_id=self.request.user.pk,
                review_name=request.POST['review_name'],
                review_content=request.POST['review_content']
            )
        except:
            pass
        return super().post(request, *args, **kwargs)
    
    
class AddProduct(CreateView):
    form_class = AddProduct
    template_name = 'products/add_product.html'
    success_url=reverse_lazy('home')
    
    def form_valid(self, form):
        w = form.save(commit=False)
        w.owner_user_id = self.request.user.pk
        return super().form_valid(form)
    
    
class UpdateProduct(UpdateView):
    model = Products
    fields = (
        'product_name',
        'product_description',
        'price',
        'quantity',
        'product_cat',
        'product_img',
        'public'
    )
    template_name = 'products/update_product.html'
    success_url = reverse_lazy('home')

store_django/products/templates/products/add_product.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить продукт</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Добавить</button>
    </form>
</body>
</html>

store_django/products/templates/products/add_review.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Добавить отзыв</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Довавить</button>
    </form>
</body>
</html>

store_django/products/templates/products/categorys.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% for i in data %}
    <br>
    <div>
        <p>id {{i.pk}}</p>
        <p>name {{i.cat_name}}</p>
    </div>
    {% endfor %}
</body>
</html>

store_django/products/templates/products/main.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Main</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <div>
        <form method="post">
            {% csrf_token %}
            <select name="product_cat" id="product_cat">
                <option value="11">для спорта</option>
                <option value="12">для дома</option>
                <option value="13">одежда</option>
                <option value="14">для школы</option>
                <option value="15">игрушки</option>
                <option value="16">медицинское</option>
                <option value="all">все категории</option>
            </select>
            <button name="button" value="filter" type="submit">Отфильтровать</button>
            <button type="button">
                <a href="{% url 'users:register' %}">Регистрация</a>
            </button>
            <button type="button">
                <a href="{% url 'users:profile' %}">Профиль</a>
            </button>
            <button type="button">
                <a href="{% url 'order:applications' %}">Возвраты</a>
            </button>
        </form>
    </div>
    {% for i in products %}
    <br>
    <div>
        <img src="{{i.product_img.url}}" alt="где фото?">
        <p>Назавание товара: {{i.product_name}}</p>
    <!--<p>Опиcание товара: {{i.product_description}}</p>-->
        <p>Цена товара: {{i.price}}</p>
    <!--<p>Количество товара: {{i.quantity}}</p>-->
        <p>Категория продукта: {{i.product_cat}}</p>
        <p>Время создания продукта: {{i.product_create_time}}</p>
        <form method="post">
            {% csrf_token %}
            <button name="button" value="{{i.pk}}" type="submit">Подробнее</button>
        </form>
    </div>
    {% endfor %}
</body>
</html>

store_django/products/templates/products/product.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Product</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <div>
        <h2>Информация о продукте</h2>
        <img src="{{product.product_img.url}}" alt="где фото?">
        <h3>Продукт от: {{product.owner_user}}</h3>
        <p>Название продукта: {{product.product_name}}</p>
        <p>Описание продукта: {{product.product_description}}</p>
        <p>Цена продукта: {{product.price}}</p>
        <p>Количество продукта: {{product.quantity}}</p>
        <p>Время когда продукт был выставлен: {{product.product_create_time}}</p>
    </div>
    <br>
    <div>
        <button type="button">
            <a href="reviews/">Отзывы</a>
        </button>
        <form method="post">
            {% csrf_token %}
            <button name="button" value="hide" type="submit">Скрыть продукт</button>
            <button name="button" value="in_basket" type="submit">В корзину</button>
        </form>
        {{status}}
    </div>
</body>
</html>

store_django/products/templates/products/reviews.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Отзывы</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <button type="button">
        <a href="add_review/">Добавить отзыв</a>
    </button>
    {% for i in reviews %}
    <br>
    <div>
        <h3>{{i.owner_review}}</h3>
        <p>{{i.review_name}}</p>
        <p>{{i.review_content}}</p>
        <p>{{i.review_create_time}}</p>
        <form method="post">
            {% csrf_token %}
            <button name="button" value="{{i.pk}}" type="submit">Удалить</button>
        </form>
    </div>
    {% endfor %}
</body>
</html>

store_django/products/templates/products/update_product.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Product page</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'products/styles.css' %}">
</head>
<body>
    <form method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit">Обновить</button>
    </form>
</body>
</html>